### ISSUE TITLE
Crashes at make_soup('managemarcsubfields.edit', subfield_index)

### ISSUE THREAD

**Issue by GarrettArm** [lsulibraries/SirsiDynexFunctionalTests#1]
Tracy Rupany is experiencing this bug.  It occurs during the marcmap scraping.  (suggesting the searchfields scraping is successful).  The marcmap scraping does not complete.

Full Traceback:

Traceback (most recent call last):
File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
timeout=timeout
File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
raise value.with_traceback(tb)
File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
chunked=chunked)
File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 1321, in getresponse
response.begin()
File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 296, in begin
version, status, reason = self._read_status()
File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 265, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "scrape_Enterprise_searchconfig_marcmaps.py", line 261, in <module>
do_marcmaps()
File "scrape_Enterprise_searchconfig_marcmaps.py", line 163, in do_marcmaps
i: get_marc_info(i) for i in all_marc_codes
File "scrape_Enterprise_searchconfig_marcmaps.py", line 163, in <dictcomp>
i: get_marc_info(i) for i in all_marc_codes
File "scrape_Enterprise_searchconfig_marcmaps.py", line 189, in get_marc_info
field_marc_dict['subfields'] = parse_subfields(index)
File "scrape_Enterprise_searchconfig_marcmaps.py", line 229, in parse_subfields
subfield_page_soup = make_soup('managemarcsubfields.edit', subfield_index)
File "scrape_Enterprise_searchconfig_marcmaps.py", line 36, in make_soup
page = s.get(full_url)
File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by GarrettArm** [comment]
Some possible causes are:
 - the local internet drops for a moment, and the script is confused?
 - the Enterprise is set up so that my urls do not match other institutions?
 - the python/requests versions are different & causing some unexpected error?
 - something else?

**Comment by GarrettArm** [comment]
Tracy,  can you copy the most recent version of the script from here.  It will display each url as it attempts to scrape it.  The last url to display, post it here.

**Comment by GarrettArm** [comment]
The latest version will always be here:  https://github.com/lsulibraries/SirsiDynexFunctionalTests/blob/master/jupyter_for_requests/scrape_Enterprise_searchconfig_marcmaps.py

**Comment by komputr** [comment]
Python version 3.7.0
Enterprise version 5.0.0.5

Here is the last URL and the errors that followed:

https://search.vapld.info/client/en_US/admin/search/managemarcsubfields.edit/0
Traceback (most recent call last):
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\trupany\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\trupany\Anaconda3\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scrape_Enterprise_searchconfig_marcmaps.py", line 267, in <module>
    do_marcmaps()
  File "scrape_Enterprise_searchconfig_marcmaps.py", line 164, in do_marcmaps
    i: get_marc_info(i) for i in all_marc_codes
  File "scrape_Enterprise_searchconfig_marcmaps.py", line 164, in <dictcomp>
    i: get_marc_info(i) for i in all_marc_codes
  File "scrape_Enterprise_searchconfig_marcmaps.py", line 190, in get_marc_info
    field_marc_dict['subfields'] = parse_subfields(index)
  File "scrape_Enterprise_searchconfig_marcmaps.py", line 230, in parse_subfields
    subfield_page_soup = make_soup('managemarcsubfields.edit', subfield_index)
  File "scrape_Enterprise_searchconfig_marcmaps.py", line 37, in make_soup
    page = s.get(full_url)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\trupany\Anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by GarrettArm** [comment]
@komputr  Thanks! 

The url you named:  (https://search.vapld.info/client/en_US/admin/search/managemarcsubfields.edit/0)
Let's check if your system uses the same url for marc subfields Edit url.  

On my system, if I navigate to:  Search Configuration:  MARC Maps:   (on any marcmap, select marc21 swirly icon) Configure MARC 21 Tags:  (on any tag number, select blank page with shiny gear icon) Configure Subfield Maps:   (on any subfield character, hover over the blank page with pencil icon) Edit icon.  What is the url displayed in the bottom of the browser for this Edit icon?

I'm attaching a screenshot of what this looks like on my library's system.  
![enterprisemarcsubfield](https://user-images.githubusercontent.com/6989085/48854247-08d70300-ed77-11e8-84e4-09d5aa0cd700.png)

Confirm for me the url for that circled icon, please.

**Comment by komputr** [comment]
Looks the same:
https://search.vapld.info/client/en_US/admin/search/managemarcsubfields.edit/0

**Comment by GarrettArm** [comment]
Confusing.  
When you click the icon with that url in the GUI, it works?  (the url will not work directly, that's normal.  It should work when accessed through the page displayed in the photo above.  The same as clicking the blank page with pencil icon.).
The searchfields json file is created correctly & is readable?

**Comment by komputr** [comment]
The Enterprise Admin GUI works fine. The searchfields json file imports great into Excel using the Power Query Editor. I wonder if the requests are coming in too fast for the server and they are terminating my connection? Could we slow it down a bit and see if that helps?

**Comment by komputr** [comment]
Or maybe break it into two parts so the searchfields runs separately from the marcmaps?

**Comment by GarrettArm** [comment]
@komputr 
When you get a chance, will you pull the most recent version & run it?  I made it more tolerant to network drops, which may be the problem.
If this new version doesn't fix it -- uncomment the "do_verbose_logging()" at line 290, and post the last few dozen lines of that debug output.  

Thanks for working with me on this.  You're making it better for the next user.
garrett

**Comment by komputr** [comment]
Thank you for all your work on this! It will save me hours of mind-numbing copy & paste operations! This version completed successfully! 🥇

**Comment by GarrettArm** [comment]
Yes!  High-five
